#!/bin/bash

echo "=========================================="
echo "   DEPLOYMENT GUIDE"
echo "=========================================="
echo ""
echo "Option 1: Quick Cloud Deployment (Recommended)"
echo "----------------------------------------------"
echo ""
echo "1. Deploy Frontend (Vercel - FREE):"
echo "   cd frontend"
echo "   npm install -g vercel"
echo "   vercel"
echo ""
echo "2. Deploy Backend (Railway - FREE):"
echo "   - Go to: https://railway.app"
echo "   - New Project → Deploy from GitHub"
echo "   - Select backend folder"
echo "   - Add environment variables:"
echo "     * SUPABASE_URL"
echo "     * SUPABASE_ANON_KEY"
echo ""
echo "3. Update frontend/.env.production:"
echo "   NEXT_PUBLIC_API_URL=https://your-backend.railway.app"
echo ""
echo "4. Redeploy frontend:"
echo "   vercel --prod"
echo ""
echo "5. Share the Vercel URL with others!"
echo ""
echo "=========================================="
echo ""
echo "Option 2: Create Local Desktop App"
echo "----------------------------------------------"
echo ""
echo "This creates a simple launcher for local use:"
echo "   ./create-desktop-app.sh"
echo ""
echo "=========================================="
